### PR TITLE
Custom props for input components

### PR DESCRIPTION
**Pull request by algm**
I added an option for inputs that you can use to set custom props in input components.
Using this we should be able to fix issue #30 with not much effort and also add more flexibility to the component for interaction with external UI.

### CODE REVIEW

**Comment by algm** [comment]
Issue #30 should now be also fixed with commit f79cf51

**Comment by andrewhathaway** [comment]
Hi @algm.

Is there any chance you can look in to this not merging automatically while I look at some other issues? Getting ready to push a new version when this is done! 

Thanks.

**Comment by algm** [comment]
Right now I am a bit busy with other things, but I'll try to take a look at it tomorrow :)

**Comment by andrewhathaway** [comment]
Awesome. Thank you very much @algm.

New version is a go!

**Pull request merged**
