### PR TITLE
Add label/input associations for accessibility

### PR DESCRIPTION
**Pull request by jwbrady**
[Part of the WCAG guidelines is to associate form labels with their inputs](http://www.w3.org/TR/WCAG20-TECHS/H44.html). This change enables them for all but checkboxes radio buttons, and hidden inputs.

### CODE REVIEW

**Comment by jwbrady** [comment]
First use of pull requests. Not sure how to best update them.

**Comment by jwbrady** [comment]
A force push worked, even though it didn't show it for a little while. What is the best way to update a pull-request? I forgot to update the default props.

**Comment by iamthemovie** [comment]
Rebase it.

**Comment by andrewhathaway** [comment]
Hi @jwbrady.

You should never use a force push. The reason you had to force push is because the code has changed a fair amount since you last pushed. For this reason, I'm going to have to close this PR and ask you to re-fork and submit another PR please!

Thanks.

**Comment by jwbrady** [comment]
Sorry about that. Will do!

**Pull request closed without merging**
